plugins:
#定义了一个带过期缓存的内部使用/外部使用的国内dns服务器
#转发请求到国内dns
  # - tag: forward_local
  #   type: forward
  #   args:
  #     concurrent: 3
  #     upstreams:
  #       - addr: "223.5.5.5"
  #       - addr: "quic://223.5.5.5"
  #       - addr: "202.102.128.68"
  #         upstream_query_timeout: 500
  - tag: forward_local
    type: aliapi
    args:
      concurrent: 3
      account_id: "111111"
      access_key_id: "222222"
      access_key_secret: "333333"
      server_addr: "223.5.5.5"
      upstreams:
        - tag: alidns
          type: aliapi  
        - addr: "202.102.128.68"
          upstream_query_timeout: 500


#国内域名 内部使用
  - tag: sequence_local_in
    type: sequence
    args:
      - matches: switch4 'A'
        exec: $cache_cn
      - matches:
        - switch4 'A'
        - has_resp
        exec: accept
      - exec: $forward_local

#国内
  - tag: udp_local
    type: udp_server
    args:
      entry: sequence_local_in
      listen: ":2222"

  - tag: tcp_local
    type: tcp_server
    args:
      entry: sequence_local_in
      listen: ":2222"