global:
  scrape_interval: 1m
  evaluation_interval: 1m
alerting:
  alertmanagers:
rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "mosdns"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8338"]